spring:
  profiles:
    active: one
management:
  security:
    enabled: false
endpoints:
  shutdown:
    enabled: true
logging:
  level: error
#logging:
#  level:
#   root: trace
#   org:
#    apache: info
#    springframework: trace
#   javax: info