spring:
  profiles:
    active: one
management:
  security:
    enabled: false
endpoints:
  shutdown:
    enabled: true
logging:
  level: error
#server:
#  tomcat:
#    accesslog:
#      enabled: true
#      directory: /opt/idea/workspace/Spring-Cloud-Study/Spring-Boot/src/main/resources/
#logging:
#  level:
#   root: trace
#   org:
#    apache: info
#    springframework: trace
#   javax: info