#FROM java:8
#VOLUME /opt
#COPY ../../../../../target/Spring-Cloud-Ribbon-0.0.1-SNAPSHOT.jar ribbon.jar
#RUN bash -c 'touch /ribbon.jar'
#EXPOSE 8081
#ENTRYPOINT ["java", "-jar", "/ribbon.jar"]

#https://gitbj.cmcm.com/NaughtyCheetahStudio/ArrowBrawl/AB-dcserver.git