server:
  port: 9051

spring:
  application:
    name: cloud-feign-consumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
feign:
  hystrix:
    enabled: true

#Ribbon 超时时间设置
#ribbon:
#  ConnectTimeout: 500
#  ReadTimeout:  3000