server:
  port: 9051
spring:
  application:
    name: cloud-feign-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://spontaneously:123456@localhost:8080/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
logging:
  level:
    root: info
#Ribbon 超时时间设置
#ribbon:
#  ConnectTimeout: 500
#  ReadTimeout:  3000
